### ISSUE TITLE
portrait display

### ISSUE THREAD

**Issue by msliczniak** [andrewstephens75/as-dithered-image#2] opened 2022-12-19 17:00 UTC
macos 12.6.1

google chrome Version 107.0.5304.87 (Official Build) (x86_64)

scaled 1024x1280 90* rotation

https://imgur.com/7LSD7BX

same result in safari, works on firefox though

**Comment by andrewstephens75** [comment] 2022-12-19 17:47
Thanks for your feedback. I am unable to reproduce this problem on MacOSX13.1 (the only version I have to hand right now). I did fix a similar problem a couple of hours ago - try force-refreshing the page to see if the new version fixes it.

**Comment by msliczniak** [comment] 2022-12-19 18:12
it works now, thanks

**Comment by andrewstephens75** [comment] 2022-12-19 18:42
Closing as fixed (in a previous version)

**Closed** 2022-12-19 18:43 UTC
